version: 0.0
os: linux
files:
  - source: /source-code-<commit-hash>.zip
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/verify_deployment.sh
      timeout: 300
      runas: root
